import http from 'node:http';
import { createHash, randomBytes } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const dataDir=path.join(root,'.data');
await mkdir(dataDir,{recursive:true});
for(const envFile of ['.env.local','.env']) if(existsSync(path.join(root,envFile))){
  const body=await readFile(path.join(root,envFile),'utf8');
  for(const line of body.split(/\r?\n/)){const m=line.match(/^([A-Z0-9_]+)=(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].trim().replace(/^['"]|['"]$/g,'')}
}
const cfg={clientId:process.env.CA_CLIENT_ID||'',secret:process.env.CA_CLIENT_SECRET||'',redirect:process.env.CA_REDIRECT_URI||'http://127.0.0.1:8787/auth/conta-azul/callback',front:process.env.CA_FRONTEND_URL||'http://127.0.0.1:5173',port:Number(process.env.CA_PORT||8787)};
const files={sessions:path.join(dataDir,'ca-sessions.json'),mappings:path.join(dataDir,'ca-mappings.json'),created:path.join(dataDir,'ca-created.json')};
const houses=new Set(['Bafo da Prainha','Capiau','Dois de Fevereiro','Casa Porto','Casa de Apoio CRS']);
const states=new Map();
const readJson=async(file,fallback)=>{try{return JSON.parse(await readFile(file,'utf8'))}catch{return fallback}};
const saveJson=(file,value)=>writeFile(file,JSON.stringify(value,null,2),'utf8');
const json=(res,status,body)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(body))};
const readBody=async req=>{let body='';for await(const chunk of req){body+=chunk;if(body.length>1e6)throw new Error('Corpo muito grande')}return body?JSON.parse(body):{}};
const configured=()=>Boolean(cfg.clientId&&cfg.secret);
const requireHouse=value=>{const house=String(value||'');if(!houses.has(house))throw new Error('Selecione uma casa válida');return house};
async function token(house){const sessions=await readJson(files.sessions,{});let current=sessions[house];if(!current)throw new Error(`Conta Azul de ${house} não conectada`);if(current.expires_at>Date.now()+60000)return current.access_token;const form=new URLSearchParams({grant_type:'refresh_token',refresh_token:current.refresh_token});const r=await fetch('https://api-v2.contaazul.com/oauth/token',{method:'POST',headers:{authorization:'Basic '+Buffer.from(`${cfg.clientId}:${cfg.secret}`).toString('base64'),'content-type':'application/x-www-form-urlencoded'},body:form});if(!r.ok)throw new Error(`Não foi possível renovar a conexão de ${house}`);const next=await r.json();current={...current,...next,expires_at:Date.now()+(next.expires_in||3600)*1000};sessions[house]=current;await saveJson(files.sessions,sessions);return current.access_token}
async function ca(house,pathname,options={}){const access=await token(house);const r=await fetch('https://api-v2.contaazul.com'+pathname,{...options,headers:{authorization:`Bearer ${access}`,'content-type':'application/json',...(options.headers||{})}});const text=await r.text();let body;try{body=JSON.parse(text)}catch{body={message:text}}if(!r.ok)throw new Error(body?.message||body?.error_description||`Conta Azul respondeu ${r.status}`);return body}
const listOf=value=>{const raw=Array.isArray(value)?value:value?.itens||value?.items||value?.data||value?.results||value?.conteudo||[];return raw.map(x=>({id:String(x.id||x.uuid||x.id_pessoa||x.id_categoria||x.id_centro_custo||x.id_conta_financeira||''),name:String(x.nome||x.name||x.descricao||x.razao_social||x.nome_fantasia||x.apelido||'Sem nome')})).filter(x=>x.id)};
const iso=d=>{const [day,month,year]=String(d).split('/');return `${year}-${month}-${day}`};
const number=v=>Number(String(v).replace(/\./g,'').replace(',','.'));
function validate(body){const f=body.form||{},m=body.mappings||{},missing=[];if(f.kind!=='Banda')missing.push('Somente Banda está liberada nesta etapa');for(const [ok,label] of [[f.supplier,'Favorecido'],[f.amount,'Valor'],[f.payment,'Data de pagamento'],[f.competence,'Competência'],[f.description,'Descrição'],[m.contactId,'Contato no Conta Azul'],[m.categoryId,'Categoria no Conta Azul'],[m.accountId,'Conta financeira']])if(!ok)missing.push(label);if(missing.length)throw new Error('Revise: '+missing.join(', '));const amount=number(f.amount);if(!Number.isFinite(amount)||amount<=0)throw new Error('Valor inválido');return {f,m,amount}}
function payable(body){const {f,m,amount}=validate(body);const allocation={id_categoria:m.categoryId,valor:amount};if(m.costCenterId)allocation.rateio_centro_custo=[{id_centro_custo:m.costCenterId,valor:amount}];return {data_competencia:iso(f.competence),valor:amount,observacao:f.pix?`PIX: ${f.pix}`:'',descricao:f.description,contato:m.contactId,conta_financeira:m.accountId,rateio:[allocation],condicao_pagamento:{parcelas:[{descricao:f.description,data_vencimento:iso(f.payment),nota:f.bandName?`Banda: ${f.bandName}`:'',conta_financeira:m.accountId,detalhe_valor:{multa:0,juros:0,valor_bruto:amount,valor_liquido:amount,desconto:0,taxa:0},metodo_pagamento:'PIX_PAGAMENTO_INSTANTANEO'}]}}}
function fingerprint(house,payload){return createHash('sha256').update(JSON.stringify({house,contato:payload.contato,valor:payload.valor,competencia:payload.data_competencia,vencimento:payload.condicao_pagamento.parcelas[0].data_vencimento,descricao:payload.descricao})).digest('hex')}

const server=http.createServer(async(req,res)=>{try{const origin=req.headers.origin;if(origin&&(origin===cfg.front||origin==='http://localhost:5173'))res.setHeader('access-control-allow-origin',origin);res.setHeader('access-control-allow-methods','GET,POST,PUT,OPTIONS');res.setHeader('access-control-allow-headers','content-type');if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}const url=new URL(req.url,`http://${req.headers.host}`);
if(url.pathname==='/api/health')return json(res,200,{ok:true});
if(url.pathname==='/api/ca/status'){const house=requireHouse(url.searchParams.get('house'));const sessions=await readJson(files.sessions,{}),session=sessions[house];return json(res,200,{house,configured:configured(),connected:Boolean(session?.refresh_token),expiresAt:session?.expires_at||null})}
if(url.pathname==='/auth/conta-azul'){if(!configured())return json(res,400,{message:'Preencha CA_CLIENT_ID e CA_CLIENT_SECRET no arquivo .env.local'});const house=requireHouse(url.searchParams.get('house')),state=randomBytes(24).toString('hex');states.set(state,{expiresAt:Date.now()+600000,house});const query=new URLSearchParams({response_type:'code',client_id:cfg.clientId,redirect_uri:cfg.redirect,state,scope:'openid profile aws.cognito.signin.user.admin'});res.writeHead(302,{location:'https://login.contaazul.com/#/oauth/authorize?'+query.toString()});return res.end()}
if(url.pathname==='/auth/conta-azul/callback'){const code=url.searchParams.get('code'),state=url.searchParams.get('state'),pending=states.get(state);if(!code||!state||!pending||pending.expiresAt<Date.now())throw new Error('Retorno de autenticação inválido ou expirado');states.delete(state);const form=new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:cfg.redirect});const r=await fetch('https://api-v2.contaazul.com/oauth/token',{method:'POST',headers:{authorization:'Basic '+Buffer.from(`${cfg.clientId}:${cfg.secret}`).toString('base64'),'content-type':'application/x-www-form-urlencoded'},body:form});if(!r.ok)throw new Error('O Conta Azul recusou a autenticação');const session=await r.json();session.expires_at=Date.now()+(session.expires_in||3600)*1000;const sessions=await readJson(files.sessions,{});sessions[pending.house]=session;await saveJson(files.sessions,sessions);res.writeHead(302,{location:cfg.front+'?contaAzul=conectado&house='+encodeURIComponent(pending.house)});return res.end()}
if(url.pathname==='/api/ca/catalogs'&&req.method==='GET'){const house=requireHouse(url.searchParams.get('house'));const [accounts,categories,costCenters,people]=await Promise.all([ca(house,'/v1/conta-financeira?pagina=1&tamanho_pagina=100&apenas_ativo=true'),ca(house,'/v1/categorias'),ca(house,'/v1/centro-de-custo'),ca(house,'/v1/pessoas?pagina=1&tamanho_pagina=100&tipo_perfil=Fornecedor')]);return json(res,200,{house,accounts:listOf(accounts),categories:listOf(categories),costCenters:listOf(costCenters),people:listOf(people)})}
if(url.pathname==='/api/ca/mappings'){const house=requireHouse(url.searchParams.get('house'));const all=await readJson(files.mappings,{});if(req.method==='GET')return json(res,200,all[house]||{});if(req.method==='PUT'){const body=await readBody(req);all[house]=body;await saveJson(files.mappings,all);return json(res,200,body)}}
if(url.pathname==='/api/ca/payables/preview'&&req.method==='POST'){const body=await readBody(req),house=requireHouse(body.house),payload=payable(body);return json(res,200,{house,payload,fingerprint:fingerprint(house,payload)})}
if(url.pathname==='/api/ca/payables'&&req.method==='POST'){const body=await readBody(req),house=requireHouse(body.house);if(body.confirm!==true)throw new Error('A confirmação final é obrigatória');const payload=payable(body),key=fingerprint(house,payload),created=await readJson(files.created,{});if(created[key])return json(res,200,{...created[key],duplicatePrevented:true});const result=await ca(house,'/v1/financeiro/eventos-financeiros/contas-a-pagar',{method:'POST',body:JSON.stringify(payload)});const saved={house,protocolId:result.protocolo||result.protocolId||result.id||'',status:result.status||'PROCESSANDO',createdAt:result.data_criacao||result.createdAt||new Date().toISOString()};created[key]=saved;await saveJson(files.created,created);return json(res,202,saved)}
return json(res,404,{message:'Rota não encontrada'});
}catch(error){return json(res,400,{message:error instanceof Error?error.message:'Erro inesperado'})}});
server.listen(cfg.port,'127.0.0.1',()=>console.log(`Servidor Conta Azul em http://127.0.0.1:${cfg.port}`));
